### ISSUE TITLE
Support analysis script configuration from yaml

### ISSUE THREAD

**Issue by eckelsjd** [JANUS-Institute/HallThrusterPEM#27]
I'm adding this as a potential cool future improvement to streamline the analysis scripts.

What if — just like a PEM is fully specifiable from a single config file — we also made a full "analysis" configurable from a single file? We can already kind of see how many options there are with the CLI for `train.sh` — I've even added `train-shim.sh` files just so you don't have to type all the arguments out. I'm imagining a yaml configuration like this:

```yaml
analyses:
  - train:
    num_samples: 1000
    executor: process
    other 'train' options...
  - mcmc:
    num_samples: 5000
    etc.
  - sobol:
  - other analyses ...   
```

This way, you could mix and match entire PEM versions with entire sets of analyses via a CLI like this:

```shell
run my_analysis.yml pem_version.yml
```
